In [1]:
import os
os.chdir("..")
os.getcwd()

'D:\\repositories\\PyFlowSolver'

In [2]:
%run .\pyflowsolver\volumeManager.py
%run .\pyflowsolver\sparseArray.py
%run .\pyflowsolver\velocityArray.py
%run .\pyflowsolver\stokesSolver.py

In [3]:
vol = np.ones((3,3,3), dtype=np.float32)
vol[1,0,1] = 0
vol[1,2,1] = 0
volume_manager = VolumeManager(vol)

In [4]:
stokes_solver = StokesSolver(volume_manager)
stokes_solver.create_velocity_arrays()
for x, y, z in ((c,b,a) for a in range(4) for b in range(3) for c in range(3)):
    try:
        stokes_solver.set_x_vel_in(x, y, z, x + 10*y + 100*z)
    except Exception as e:
        print(e)
    try:
        stokes_solver.set_y_vel_in(x, y, z, x + 10*y + 100*z)
    except Exception as e:
        print(e)
    try:
        stokes_solver.set_z_vel_in(x, y, z, x + 10*y + 100*z)
    except Exception as e:
        print(e)
    try:
        stokes_solver.set_pressure(x, y, z, x + 10*y + 100*z)
    except Exception as e:
        print(e)

Trying to set x velocity in boudary at coords [0,0,0]
Trying to set y velocity in boudary at coords [0,0,0]
Trying to set y velocity in boudary at coords [1,0,0]
Trying to set y velocity in boudary at coords [2,0,0]
Trying to set x velocity in boudary at coords [0,1,0]
Trying to set x velocity in boudary at coords [0,2,0]
Trying to set x velocity in boudary at coords [0,0,1]
Trying to set y velocity in boudary at coords [0,0,1]
Trying to set x velocity in boudary at coords [1,0,1]
Trying to set y velocity in boudary at coords [1,0,1]
Trying to set z velocity in boudary at coords [1,0,1]
Trying to set pressure in solid at coords [1,0,1]
Trying to set x velocity in boudary at coords [2,0,1]
Trying to set y velocity in boudary at coords [2,0,1]
Trying to set x velocity in boudary at coords [0,1,1]
Trying to set y velocity in boudary at coords [1,1,1]
Trying to set x velocity in boudary at coords [0,2,1]
Trying to set x velocity in boudary at coords [1,2,1]
Trying to set y velocity in boud

In [5]:
print(stokes_solver.x_vel_nulls_count_array)
print(stokes_solver.y_vel_nulls_count_array)
print(stokes_solver.z_vel_nulls_count_array)

[0 0 0 0 0 0 1 2 2 2 3 4 4 4 4 4 4 4]
[0 0 0 0 0 0 0 1 1 1 2 2 2 2 2 2 2 2]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4]


In [6]:
for x, y, z in ((c,b,a) for a in range(3) for b in range(3) for c in range(3)):
    print(f"[{x},{y},{z}", stokes_solver.get_voxel_info(x, y, z))

[0,0,0 {'x_vel_in': 0.0, 'x_vel_out': 1.0, 'y_vel_in': 0.0, 'y_vel_out': 10.0, 'z_vel_in': 0.0, 'z_vel_out': 100.0, 'pressure': 0.0}
[1,0,0 {'x_vel_in': 1.0, 'x_vel_out': 2.0, 'y_vel_in': 0.0, 'y_vel_out': 11.0, 'z_vel_in': 1.0, 'z_vel_out': 0.0, 'pressure': 1.0}
[2,0,0 {'x_vel_in': 2.0, 'x_vel_out': 0.0, 'y_vel_in': 0.0, 'y_vel_out': 12.0, 'z_vel_in': 2.0, 'z_vel_out': 102.0, 'pressure': 2.0}
[0,1,0 {'x_vel_in': 0.0, 'x_vel_out': 11.0, 'y_vel_in': 10.0, 'y_vel_out': 20.0, 'z_vel_in': 10.0, 'z_vel_out': 110.0, 'pressure': 10.0}
[1,1,0 {'x_vel_in': 11.0, 'x_vel_out': 12.0, 'y_vel_in': 11.0, 'y_vel_out': 21.0, 'z_vel_in': 11.0, 'z_vel_out': 111.0, 'pressure': 11.0}
[2,1,0 {'x_vel_in': 12.0, 'x_vel_out': 0.0, 'y_vel_in': 12.0, 'y_vel_out': 22.0, 'z_vel_in': 12.0, 'z_vel_out': 112.0, 'pressure': 12.0}
[0,2,0 {'x_vel_in': 0.0, 'x_vel_out': 21.0, 'y_vel_in': 20.0, 'y_vel_out': 0.0, 'z_vel_in': 20.0, 'z_vel_out': 120.0, 'pressure': 20.0}
[1,2,0 {'x_vel_in': 21.0, 'x_vel_out': 22.0, 'y_vel_in'